name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  deployment_status:

jobs:
  check-bats-version:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment != 'Production'
    runs-on: ubuntu-latest
    steps:
      - run: echo github.event.deployment_status.state is ${{ github.event.deployment_status.state }}
      - run: echo github.event.deployment.environment is ${{ github.event.deployment.environment }}
